### ISSUE TITLE
New High score makes dino to jump

### ISSUE THREAD

**Issue by shubhamwaghe** [iashris/TREX#2]
Making a new high score makes a beep sound. This triggers an unwanted jump which generally makes the game over...
`this.playSound(this.soundFx.SCORE);`
Nice work btw man!

**Comment by iashris** [comment]
Thank you Shubham! 
Made the edits here. https://github.com/ashris/TREX | https://ashris.github.io/TREX/ )
The audio input doesn't work for http sites and hence I had to shift the repo from this account that is linked to http://iashris.com

**Comment by shubhamwaghe** [comment]
Yeah, perfect, was going to tell the same, Readme.md link "go and enjoy!"
needs update.  👍
ᐧ
